### ISSUE TITLE
Replace bad-words DB

### ISSUE THREAD

**Issue by ai** [y-gagar1n/nanoid-good#1]
There are 2 big problems with `bad-words`:

1. JS is too big (especially compared to Nano ID).
2. It doesn’t contain non-English bad words.

There is a better DBs on npm. Or we can create separated npm package with [thisl list](https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words) in the single JS file.

**Comment by y-gagar1n** [comment]
Thanks for the suggestion! I'll see what I can do.

**Comment by alex7kom** [comment]
https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words is actually not really good either. First, It's tailored to filter offensive things that may appear on photos since it's created by a photo stock site. Then it has questionable transliterations for Russian words, and for some reason no transliterations for CJK at all.

**Comment by y-gagar1n** [comment]
The problem here is that https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words is about 2-3 times bigger than `bad-words`. 
I've made an implementation using `naughty-words`, (npm package with words from LDNOOBW) in branch [replace-badwords](https://github.com/y-gagar1n/nanoid-good/tree/replace-badwords) but I'm not publishing it yet because the package size grew significantly.

Now I'm looking for ways to let user configure which languages he wants to use.

**Comment by y-gagar1n** [comment]
What I like in `bad-words` is that it contains a lot of variations of words, words with spelling errors, words with letters replaced by numbers (like`p0rn`) and such. There words are likely to occur in automatically generated IDs.

**Comment by ai** [comment]
Good point. We can use it together with a different DB.

**Comment by alex7kom** [comment]
Unfortunately, I don't have a specific db in mind, though I believe there are plenty of more comprehensive lists.

Also, some ideas to save space:
Spelling/number variations of words can be generated on the fly. For number variations generated id can be normalized before comparing.
Long phrases and words can be removed or reduced to word roots.

**Comment by ai** [comment]
Good idea. We can try to create `bad-ids` npm package.

**Comment by y-gagar1n** [comment]
@ai could you please look through the PR and maybe give some advice?
